"""empty message

Revision ID: 62368b3e883f
Revises: 
Create Date: 2023-03-23 16:27:01.298224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62368b3e883f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('week',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monday_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('week', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_week_monday_date'), ['monday_date'], unique=True)

    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availability_weekday'), ['weekday'], unique=False)

    op.create_table('day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('projected_sales', sa.Integer(), nullable=True),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['week_id'], ['week.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_day_date'), ['date'], unique=True)

    op.create_table('request_off',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_off', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_off_end'), ['end'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_off_start'), ['start'], unique=False)

    op.create_table('work_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['day.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_block')
    with op.batch_alter_table('request_off', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_off_start'))
        batch_op.drop_index(batch_op.f('ix_request_off_end'))

    op.drop_table('request_off')
    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_day_date'))

    op.drop_table('day')
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availability_weekday'))

    op.drop_table('availability')
    with op.batch_alter_table('week', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_week_monday_date'))

    op.drop_table('week')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_position'))
        batch_op.drop_index(batch_op.f('ix_user_last_name'))
        batch_op.drop_index(batch_op.f('ix_user_first_name'))

    op.drop_table('user')
    # ### end Alembic commands ###
