"""empty message

Revision ID: 812bb91c11aa
Revises: 3f44d0bda9ea
Create Date: 2023-03-17 17:25:01.121321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812bb91c11aa'
down_revision = '3f44d0bda9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_off', schema=None) as batch_op:
        batch_op.alter_column('start',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=40),
               existing_nullable=True)
        batch_op.alter_column('end',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=40),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('request_off', schema=None) as batch_op:
        batch_op.alter_column('end',
               existing_type=sa.String(length=40),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('start',
               existing_type=sa.String(length=40),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
