"""empty message

Revision ID: 193397ecaa98
Revises: cd5c1fb1ee59
Create Date: 2020-08-08 15:57:29.604978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193397ecaa98'
down_revision = 'cd5c1fb1ee59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day', sa.Column('state', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day', 'state')
    # ### end Alembic commands ###
