"""empty message

Revision ID: 39d28de5076b
Revises: 664557730b16
Create Date: 2021-10-14 12:34:43.830022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d28de5076b'
down_revision = '664557730b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day', sa.Column('projected_sales', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day', 'projected_sales')
    # ### end Alembic commands ###
