"""empty message

Revision ID: 458bf9ee79ee
Revises: 92d95f27330c
Create Date: 2022-04-11 20:51:55.044020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458bf9ee79ee'
down_revision = '92d95f27330c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day', sa.Column('week_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'day', 'week_schedule', ['week_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'day', type_='foreignkey')
    op.drop_column('day', 'week_id')
    # ### end Alembic commands ###
