"""empty message

Revision ID: 92d95f27330c
Revises: 8c2bac8ca794
Create Date: 2022-04-11 20:44:31.554935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d95f27330c'
down_revision = '8c2bac8ca794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('week_schedule', sa.Column('monday_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('week_schedule', 'monday_date')
    # ### end Alembic commands ###
