"""empty message

Revision ID: cd5c1fb1ee59
Revises: ac28872ad938
Create Date: 2020-08-08 15:53:09.992731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5c1fb1ee59'
down_revision = 'ac28872ad938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_avail_restriction_weekday', table_name='avail_restriction')
    op.drop_table('avail_restriction')
    op.drop_index('ix_off_days_day', table_name='off_days')
    op.drop_index('ix_off_days_month', table_name='off_days')
    op.drop_index('ix_off_days_year', table_name='off_days')
    op.drop_table('off_days')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('off_days',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('day', sa.INTEGER(), nullable=True),
    sa.Column('month', sa.INTEGER(), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_off_days_year', 'off_days', ['year'], unique=False)
    op.create_index('ix_off_days_month', 'off_days', ['month'], unique=False)
    op.create_index('ix_off_days_day', 'off_days', ['day'], unique=False)
    op.create_table('avail_restriction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('weekday', sa.INTEGER(), nullable=True),
    sa.Column('start_time', sa.INTEGER(), nullable=True),
    sa.Column('end_time', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_avail_restriction_weekday', 'avail_restriction', ['weekday'], unique=False)
    # ### end Alembic commands ###
