"""empty message

Revision ID: daeea6e0ea66
Revises: 1d397f5c053e
Create Date: 2020-08-11 12:43:14.914687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daeea6e0ea66'
down_revision = '1d397f5c053e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day', sa.Column('state', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day', 'state')
    # ### end Alembic commands ###
