"""empty message

Revision ID: e01f9ba2dad6
Revises: a1ea33a80e2a
Create Date: 2020-07-22 13:15:38.676797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01f9ba2dad6'
down_revision = 'a1ea33a80e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_day_day'), 'day', ['day'], unique=False)
    op.create_index(op.f('ix_day_month'), 'day', ['month'], unique=False)
    op.create_index(op.f('ix_day_year'), 'day', ['year'], unique=False)
    op.create_table('work_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['day.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_block_end_time'), 'work_block', ['end_time'], unique=False)
    op.create_index(op.f('ix_work_block_start_time'), 'work_block', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_block_start_time'), table_name='work_block')
    op.drop_index(op.f('ix_work_block_end_time'), table_name='work_block')
    op.drop_table('work_block')
    op.drop_index(op.f('ix_day_year'), table_name='day')
    op.drop_index(op.f('ix_day_month'), table_name='day')
    op.drop_index(op.f('ix_day_day'), table_name='day')
    op.drop_table('day')
    # ### end Alembic commands ###
