"""empty message

Revision ID: fb4f1fcb8204
Revises: e01f9ba2dad6
Create Date: 2020-07-23 14:10:38.498641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4f1fcb8204'
down_revision = 'e01f9ba2dad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_work_block_end_time', table_name='work_block')
    op.drop_index('ix_work_block_start_time', table_name='work_block')
    op.drop_table('work_block')
    op.drop_table('schedule')
    op.drop_index('ix_day_day', table_name='day')
    op.drop_index('ix_day_month', table_name='day')
    op.drop_index('ix_day_year', table_name='day')
    op.drop_table('day')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('month', sa.INTEGER(), nullable=True),
    sa.Column('day', sa.INTEGER(), nullable=True),
    sa.Column('schedule_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_day_year', 'day', ['year'], unique=False)
    op.create_index('ix_day_month', 'day', ['month'], unique=False)
    op.create_index('ix_day_day', 'day', ['day'], unique=False)
    op.create_table('schedule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_block',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=True),
    sa.Column('start_time', sa.INTEGER(), nullable=True),
    sa.Column('end_time', sa.INTEGER(), nullable=True),
    sa.Column('day_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['day.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_work_block_start_time', 'work_block', ['start_time'], unique=False)
    op.create_index('ix_work_block_end_time', 'work_block', ['end_time'], unique=False)
    # ### end Alembic commands ###
