"""empty message

Revision ID: fcd94e320ae6
Revises: 193397ecaa98
Create Date: 2020-08-11 12:19:15.179691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd94e320ae6'
down_revision = '193397ecaa98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day', sa.Column('state', sa.VARCHAR(length=25), nullable=True))
    # ### end Alembic commands ###
